init
playmixer/gophermart pull request #1
Opened 2024-07-13 07:42 UTC by playmixer

2024-07-22 13:36 UTC, s-shpak requested changes
1. Graceful shutdown пока не реализован: все горутины должны быть завершены до завершения процесса

2024-07-22 13:36 UTC, s-shpak commented on deploy/gophermart/Dockerfile
> +COPY cmd/gophermart/main.go ./
А зачем это? Почему бы не сбилдить бинарь по оригинальному пути ?

2024-07-22 13:36 UTC, s-shpak commented on docs/docs.go
> +// Package docs Code generated by swaggo/swag. DO NOT EDIT
Скажи, пожалуйста, а есть-ли инструкции по перегенерации документации (при изменении эндпоинта, например)

2024-07-22 13:36 UTC, s-shpak commented on docs/swagger.yaml
> +basePath: /
Это сгенерированный файл или добавленный вручную ? Тот же вопрос про json-файл

2024-07-22 13:36 UTC, s-shpak commented on cmd/gophermart/main.go
> +	if err := run(); !errors.Is(err, http.ErrServerClosed) {
А зачем ловить эту ошибку здесь ? Почему бы не сделать это в `tun()` ?

2024-07-22 13:36 UTC, s-shpak commented on internal/core/config/config.go
> +	if err := env.Parse(cfg); err != nil {
Сейчас ведь переменные окружения приоритетны над флагами ? Мы обсуждали на вебинаре, должно быть наоборот: дефолтные значения < файл-конфигурации < переменные окружения < флаги

2024-07-22 13:36 UTC, s-shpak commented on internal/core/config/config.go
> +	_ = godotenv.Load(".env")
Почему ошибка здесь не проверяется ?

2024-07-22 13:36 UTC, s-shpak commented on internal/core/config/config.go
> +			GorutineEnabled: true,
Это захардкоженное значение ? Может сделать его параметризуемым ?

2024-07-22 13:36 UTC, s-shpak commented on internal/adapters/api/rest/rest.go
> +		address: ":8080",
Лучше перенести это дефолтное значение туда, где происходит работа с конфигуарцией

2024-07-22 13:36 UTC, s-shpak commented on internal/adapters/api/rest/rest.go
> +		secret:  []byte("default_secret_key"),
Аналогично пердыдущему

2024-07-22 13:36 UTC, s-shpak commented on internal/adapters/api/rest/rest.go
> +func (s *Server) CreateEngine() *gin.Engine {
Почему это эксмопртируемая функция ?

2024-07-22 18:45 UTC, playmixer commented on docs/docs.go
> +// Package docs Code generated by swaggo/swag. DO NOT EDIT
> Скажи, пожалуйста, а есть-ли инструкции по перегенерации документации (при изменении эндпоинта, например)

команда для перегенерации: swag init -o ./docs -g ./internal/adapters/api/rest/rest.go
+ добавил в редми и ссылку на документакцию если вдруг

2024-07-22 18:46 UTC, playmixer commented on docs/swagger.yaml
> +basePath: /
> Это сгенерированный файл или добавленный вручную ? Тот же вопрос про json-файл

это сгенерированный файл, и все остальные файлы в директории docs тоже сгенерированы автоматически

2024-07-23 06:53 UTC, playmixer commented on internal/adapters/api/rest/rest.go
> +func (s *Server) CreateEngine() *gin.Engine {
> Почему это эксмопртируемая функция ?

я его сделал публичным, что бы можно было использовать в тестах, тесты у меня по методу черного ящика

2024-07-23 09:15 UTC, playmixer commented on deploy/gophermart/Dockerfile
> +COPY cmd/gophermart/main.go ./
> А зачем это? Почему бы не сбилдить бинарь по оригинальному пути ?

не очень понял в чем разница, добавил по оригинальному пути

2024-07-23 09:17 UTC, playmixer commented on internal/core/config/config.go
> +	if err := env.Parse(cfg); err != nil {
исправил

2024-07-23 09:23 UTC, playmixer commented
> 1. Graceful shutdown пока не реализован: все горутины должны быть завершены до завершения процесса

добавил

2024-07-24 23:56 UTC, s-shpak requested changes
1. Добавь, пожалуйста, в ридми сценарий тестирования сервиса

2024-07-24 23:56 UTC, s-shpak commented on go.mod
При выполнении `go mod tidy` этот файл меняется. Возможно, ты забыл настроить хуки для обновления `go.mod`

2024-07-24 23:56 UTC, s-shpak commented on internal/adapters/api/rest/rest.go
> +type Gophermart interface {
Зачем объявлен этот интерфейс ? Если для тестов, то он должен быть объявлен в другом пакете

2024-07-24 23:56 UTC, s-shpak commented on internal/adapters/api/rest/rest.go
> +	errInvalidAuthCookie = errors.New("invalid authorization cookie")
Зачем объявлена эта ошибка, если она неэкспортируется и, следовательно, нигде не проверяется ?

2024-07-24 23:56 UTC, s-shpak commented on internal/adapters/api/rest/rest.go
> +func (s *Server) CreateJWT(userID uint) (string, error) {
Почему экспортируется этот метод ?

2024-07-24 23:56 UTC, s-shpak commented on internal/adapters/api/rest/rest.go
> +func (s *Server) Run() error {
Зачем разделять создание объекта сервиса и его запуск ?

2024-07-24 23:56 UTC, s-shpak commented on internal/adapters/api/rest/rest.go
> +func (s *Server) checkAuth(c *gin.Context) (userID uint, err error) {
Почему не поместить всю эту логику в пакет middleware ?

2024-07-24 23:56 UTC, s-shpak commented on internal/adapters/api/rest/rest.go
> +		c.Writer.WriteHeader(http.StatusInternalServerError)
Ты используешь эту функцию в хендлерах (что не требуется, т.к. у тебя есть middleware) и вызываешь `WriteHeader` сначала здесь, а потом в хендлере. Не надо вызывать ее два раза

2024-07-24 23:56 UTC, s-shpak commented on internal/adapters/api/rest/rest.go
> +	if err != nil {
Странная последовательность проверок. Почему сначала не проверить `err != nil` ?

2024-07-24 23:56 UTC, s-shpak commented on internal/adapters/api/rest/middleware.go
Необходимо также реализовать сжатие ответов/разжатие запросов

2024-07-24 23:56 UTC, s-shpak commented on internal/adapters/api/rest/handler.go
> +		if err := c.Request.Body.Close(); err != nil {
Зачем закрывать тело запроса ?

2024-07-24 23:56 UTC, s-shpak commented on internal/adapters/api/rest/handler.go
> +		if errors.Is(err, gophermart.ErrLoginNotValid) || errors.Is(err, gophermart.ErrPasswordNotValid) {
Пользователю было бы полезно пояснить, что именно неверно в его запросе

2024-07-24 23:56 UTC, s-shpak commented on internal/adapters/api/rest/handler.go
> +		// c.Writer.WriteHeader(http.StatusInternalServerError)
deadcode ? Вообще, должно быть именно так, ломаются автотесты ?

2024-07-24 23:56 UTC, s-shpak commented on internal/adapters/api/rest/handler.go
> +	if err = s.authorization(c, jBody.Login, jBody.Password); err != nil {
Это можно вынести в отдельную функцию, чтобы не дублировать код в `handlerLogin`

2024-07-24 23:56 UTC, s-shpak commented on internal/adapters/api/rest/handler.go
> +			"error": err.Error(),
Пользователю нельяз отдавать внутренние ошибки

2024-07-24 23:56 UTC, s-shpak commented on internal/adapters/api/rest/handler.go
> +	bBody, err := io.ReadAll(c.Request.Body)
Здесь тоже логика, которая повторяется в `handlerRegister`

2024-07-24 23:56 UTC, s-shpak commented on internal/adapters/api/rest/handler_test.go
> +var cfg *config.Config
Глобальные перменные не нужны даже в тестах. Во-первых, они просто не нужны; во-вторых, используя их, ты рискуешь недостаточно изолировать тесты друг от друга

2024-07-24 23:56 UTC, s-shpak commented on internal/adapters/api/rest/rest.go
> +func (s *Server) CreateEngine() *gin.Engine {
Здесь возникает проблема с дизайном: для удобства тестирования ты делаешь публичным метод, который не должен быть доступен пользователю пакета. Это некорректно: тесты должны быть вторичными по отношению к логике

2024-07-24 23:56 UTC, s-shpak commented on internal/adapters/store/database/database.go
> +	if err := db.Where("status = ?", model.OrderStateNew).Or("status = ?", model.OrderStateProcessing).
Стилистическое замечание (не обязательно к правке): в таких длинных проверках не очень хорошо использовать конструкцию "if err := ; err != nil", т.к. трудно понять, где заканичвается логическое выражение, и начинается тело блока. Лучше просто вызвать `err := ...`

2024-07-24 23:56 UTC, s-shpak commented on internal/adapters/store/model/model.go
> +	ID         uint `gorm:"primarykey"`
Лучше определять структурные теги для всех полей - меньше шанс получить неожиданный и труднонаходимый баг

2024-07-24 23:56 UTC, s-shpak commented on internal/core/gophermart/gophermart.go
> +					iRetryAfter, _ := strconv.Atoi(sRetryAfter)
Ошибки надо проверять. Мы не контроллируем сервис accrual, потому не можем гарантировать, что `sRetryAfter` представляет валидное численное значение

2024-07-24 23:56 UTC, s-shpak commented on internal/core/gophermart/tools.go
> +func (s *semaphore) Lock(d time.Duration) {
Атомики сложны. Здесь, на мой взгляд, есть не очень заметный баг: представь себе, что у тебя происходит два вызова `Lock`: один в `t = 0` на `d = 10s`, второй в `t = 1` на `d = 5s`. Будет ли твоя имплементация отрабатывать корректно ?

Наверное, лучше хранить значение, когда воркеры должны проснуться как атомарную переменную и дать возможность воркерам ее прочесть

2024-07-25 05:44 UTC, playmixer commented on internal/adapters/api/rest/rest.go
> +func (s *Server) checkAuth(c *gin.Context) (userID uint, err error) {
эта логика нужна мне для получения userID из кук так же и для  хендлеров

2024-07-25 06:01 UTC, playmixer commented on internal/adapters/api/rest/handler.go
> +		if err := c.Request.Body.Close(); err != nil {
> Зачем закрывать тело запроса ?

не понял, почему его не надо закрывать? вроде ранее всегда требовалось закрывать его после чтения или я что то не так понял?

2024-07-25 10:46 UTC, playmixer commented
> 1. Добавь, пожалуйста, в ридми сценарий тестирования сервиса

добавил

2024-07-25 10:55 UTC, playmixer commented on internal/adapters/api/rest/rest.go
> +func (s *Server) Run() error {
> Зачем разделять создание объекта сервиса и его запуск ?

тут скорей я это сделал для своего удобства, и для тестов, т.к. я по фату его не запускаю в тестах, и мне нужна инициализация роутов, что бы я могу получить от него gin.Engine

2024-07-25 10:58 UTC, playmixer commented on internal/adapters/api/rest/rest.go
> +	if err != nil {
исправил

2024-07-25 10:59 UTC, playmixer commented on internal/adapters/api/rest/middleware.go
добавил

> Необходимо также реализовать сжатие ответов/разжатие запросов

2024-07-25 11:01 UTC, playmixer commented on internal/core/gophermart/tools.go
> +func (s *semaphore) Lock(d time.Duration) {
> Атомики сложны. Здесь, на мой взгляд, есть не очень заметный баг: представь себе, что у тебя происходит два вызова `Lock`: один в `t = 0` на `d = 10s`, второй в `t = 1` на `d = 5s`. Будет ли твоя имплементация отрабатывать корректно ?
> 
> Наверное, лучше хранить значение, когда воркеры должны проснуться как атомарную переменную и дать возможность воркерам ее прочесть

исправил

2024-07-30 10:40 UTC, s-shpak requested changes
Выйдай мне права в репозиторий еще раз, пожалуйста, чтобы я смог позакрывать комментарии

2024-07-30 10:40 UTC, s-shpak commented on cmd/gophermart/main.go
> +	go func() {
Пока не вижу graceful shutdown'а: неясно как серверу будет отправлен сигнал на отключение, как закроется соединение с базой и как завершится горутина, отправляющая запросы в аккруал

2024-07-30 10:40 UTC, s-shpak commented on cmd/gophermart/main.go
> +	signal.Notify(exit, os.Interrupt, syscall.SIGTERM)
Здесь можно использовать `NotifyContext`

2024-07-30 10:40 UTC, s-shpak commented on internal/core/gophermart/tools.go
> +func (s *semaphore) Lock(d time.Duration) {
Теперь ты каждый раз создаешь новый интервал. Твоя задача при получении 429 остановиться на указанный период времени и продолжить после. Если ты посылаешь `n` запросов к сервису, то первый получит задержку на 60 секунд и последний тоже. Но до следующего запроса должны пройти 60 секунд полученные после первого запроса, а не последнего. Я советую тебе упростить реализацию и сделать ее, например, при помощи паттерна Circuit Breaker (здесь есть одна из возможных имплементаций: https://github.com/sony/gobreaker)

2024-07-31 04:51 UTC, playmixer commented on cmd/gophermart/main.go
> +	go func() {
Сделал явное отключение http сервер, делал по гайду от gin 
https://gin-gonic.com/docs/examples/graceful-restart-or-stop/
добавил закрытие соединения с БД
и ожидание завершения горутин

2024-08-01 11:36 UTC, s-shpak approved these changes

2024-08-01 12:37 UTC, merged